-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."orders" add column "payment_type" text
--  not null default 'CASH';
