name: Deploy Hasura

on: workflow_dispatch

jobs:
  deploy-hasura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        uses: borales/actions-yarn@v3.0.0

      - name: Deploy
        run: |
          yarn hasura metadata apply --endpoint https://hasura.pizzastack.xyz/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }}
          yarn hasura migrate apply --endpoint https://hasura.pizzastack.xyz/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }} --database-name default
